[workspace]
name = "mit_6.824_rs"
version = "0.1.0"
edition = "2021"
resolver = "2"

members = [ "common",
	"map_reduce_task", "mr_model",
	"mr_sequential"
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"

