[workspace]
name = "mit_6.824_rs"
version = "0.1.0"
edition = "2021"
resolver = "2"

members = [
	"map_reduce_task",
	"mr_sequential"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

